version : "3"
services:
  master-db:
    image: mysql:5.7
    container_name: mysql-master
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MASTER_DB_PASSWORD}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/Shared/data/mysql-master:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
  
  slave-db:
    image: mysql:5.7
    container_name: mysql-slave
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $$SLAVE_DB_PASSWORD
      TZ : Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/Shared/data/mysql-slave:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

  test-db:
    image: mysql:5.7
    container_name: mysql-test
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${TEST_DB_PASSWORD}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/Shared/data/mysql-test:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: always